# http://travis-ci.org/#!/mengzhuo/sqlalchemy-fulltext-search
branches:
  only:
    - master
language: python
python:
    - 2.7
install:
   - "pip install -r .travis.requirements.txt --use-mirrors" 
script: "python runtests.py"
